### ISSUE TITLE
View Product Catalog

### ISSUE THREAD

**Issue by bassgt95** [GS-AlphaForceMega/graceshopper#1]
"As a visitor, I want to view the full list of products (the product catalog), so that I can see everything that's available"

**Comment by NickMaslov** [comment]
PRODUCTS
...view the full list of products (the product catalog), so that I can see everything that's available
...refine product listings by category, so that I can narrow down my choices to see only the types of items I'm interested in
...search product listings, so that I can find specific products I want by name
...view the details for an inidivdual product (including product descriptions, photos and reviews), so that I can determine whether that particular item fits my needs
