### ISSUE TITLE
Visitor - All Products - Home Page

### ISSUE THREAD

**Issue by andressantos94** [GS-AlphaForceMega/graceshopper#3]
As a visitor, I want to...view the full list of products (the product catalog), so that I can see everything that's available.

**Comment by andressantos94** [comment]
Starting trying to understand waffle.

**Comment by NickMaslov** [comment]
PRODUCTS
...view the full list of products (the product catalog), so that I can see everything that's available
...refine product listings by category, so that I can narrow down my choices to see only the types of items I'm interested in
...search product listings, so that I can find specific products I want by name
...view the details for an inidivdual product (including product descriptions, photos and reviews), so that I can determine whether that particular item fits my needs

**Comment by NickMaslov** [comment]
Home Page should include AllProducts, Header, Sidebar components

**Comment by NickMaslov** [comment]
Catalog (due Code Review 1)

Customers can browse & filter by category
Admins can add & edit products
🌟Customers can do full text search on the catalog
🌟Catalog is paginated
